import type { NoticeListResponse } from "@/api/notices/NoticeList.types";

export function getNoticeListFallback(): NoticeListResponse {
  return {
    data: [
      {
        billNo: "000000",
        viewCount: 0,
        commentsCount: 0,
        title: "데이터를 불러오지 못했습니다.",
        startDate: new Date(),
        endDate: new Date(),
        proposerImageUrl: "https://randomuser.me/api/portraits/men/14.jpg",
        mainProposer: "시스템",
        proposerParty: "무소속",
        proposers: [],
        proposerDate: new Date(),
        committee: "알 수 없음",
        currentStep: "불러오기 실패",
        stepLog: [],
        summary: "데이터를 불러오지 못했습니다.",
        agreeRatio: 0,
        opposeRatio: 0,
        detailUrl: "#",
        commentsUrl: "#",
      },
      {
        billNo: "100001",
        viewCount: 123,
        commentsCount: 10,
        title: "청년 주거 지원 강화 법안",
        startDate: new Date("2025-05-01"),
        endDate: new Date("2025-05-30"),
        proposerImageUrl: "https://randomuser.me/api/portraits/women/21.jpg",
        mainProposer: "홍길동",
        proposerParty: "더불어민주당",
        proposers: [
          { id: "1", name: "홍길동", party: "더불어민주당" },
          { id: "2", name: "김철수", party: "더불어민주당" },
        ],
        proposerDate: new Date("2025-04-20"),
        committee: "국토교통위원회",
        currentStep: "심사중",
        stepLog: ["제안", "위원회 심사"],
        summary: "청년층 주거 안정을 위한 임대 지원 법안입니다.",
        agreeRatio: 75,
        opposeRatio: 25,
        detailUrl: "#",
        commentsUrl: "#",
      },
      {
        billNo: "100002",
        viewCount: 456,
        commentsCount: 50,
        title: "노인 복지 확대 법안",
        startDate: new Date("2025-04-15"),
        endDate: new Date("2025-05-15"),
        proposerImageUrl: "https://randomuser.me/api/portraits/men/45.jpg",
        mainProposer: "이영희",
        proposerParty: "국민의힘",
        proposers: [{ id: "3", name: "이영희", party: "국민의힘" }],
        proposerDate: new Date("2025-04-10"),
        committee: "보건복지위원회",
        currentStep: "본회의 통과",
        stepLog: ["제안", "위원회 심사", "본회의 의결"],
        summary: "노인 복지 향상을 위한 의료비 지원 확대 법안입니다.",
        agreeRatio: 60,
        opposeRatio: 40,
        detailUrl: "#",
        commentsUrl: "#",
      },
      {
        billNo: "100003",
        viewCount: 89,
        commentsCount: 5,
        title: "환경 보호를 위한 탄소세 도입 법안",
        startDate: new Date("2025-06-01"),
        endDate: new Date("2025-06-30"),
        proposerImageUrl: "https://randomuser.me/api/portraits/women/32.jpg",
        mainProposer: "박민정",
        proposerParty: "정의당",
        proposers: [{ id: "4", name: "박민정", party: "정의당" }],
        proposerDate: new Date("2025-05-20"),
        committee: "환경노동위원회",
        currentStep: "위원회 계류",
        stepLog: ["제안"],
        summary:
          "환경 보호를 위해 탄소 배출량에 따른 세금을 부과하는 법안입니다.",
        agreeRatio: 50,
        opposeRatio: 50,
        detailUrl: "#",
        commentsUrl: "#",
      },
      {
        billNo: "100004",
        viewCount: 0,
        commentsCount: 0,
        title: "데이터를 불러오지 못했습니다.",
        startDate: new Date(),
        endDate: new Date(),
        proposerImageUrl: "https://randomuser.me/api/portraits/men/14.jpg",
        mainProposer: "시스템",
        proposerParty: "무소속",
        proposers: [],
        proposerDate: new Date(),
        committee: "알 수 없음",
        currentStep: "불러오기 실패",
        stepLog: [],
        summary: "데이터를 불러오지 못했습니다.",
        agreeRatio: 0,
        opposeRatio: 0,
        detailUrl: "#",
        commentsUrl: "#",
      },
      {
        billNo: "100005",
        viewCount: 300,
        commentsCount: 100,
        title: "기본소득 도입을 위한 법안",
        startDate: new Date("2025-07-01"),
        endDate: new Date("2025-12-31"),
        proposerImageUrl: "https://randomuser.me/api/portraits/men/55.jpg",
        mainProposer: "김기본",
        proposerParty: "기본소득당",
        proposers: [
          { id: "5", name: "김기본", party: "기본소득당" },
          { id: "6", name: "이소득", party: "기본소득당" },
        ],
        proposerDate: new Date("2025-06-15"),
        committee: "재정경제위원회",
        currentStep: "발의",
        stepLog: ["발의"],
        summary: "모든 국민에게 정기적으로 기본소득을 지급하는 법안입니다.",
        agreeRatio: 90,
        opposeRatio: 10,
        detailUrl: "#",
        commentsUrl: "#",
      },
      {
        billNo: "100006",
        viewCount: 150,
        commentsCount: 1,
        title: "국방 예산 증액 법안",
        startDate: new Date("2025-03-01"),
        endDate: new Date("2025-09-30"),
        proposerImageUrl: "https://randomuser.me/api/portraits/men/66.jpg",
        mainProposer: "최강국",
        proposerParty: "국민의힘",
        proposers: [{ id: "7", name: "최강국", party: "국민의힘" }],
        proposerDate: new Date("2025-02-20"),
        committee: "국방위원회",
        currentStep: "폐기",
        stepLog: ["제안", "위원회 심사", "폐기"],
        summary: "국방 예산을 대폭 증액하는 법안이었으나 폐기되었습니다.",
        agreeRatio: 20,
        opposeRatio: 80,
        detailUrl: "#",
        commentsUrl: "#",
      },
      {
        billNo: "100007",
        viewCount: 220,
        commentsCount: 500,
        title: "초중고 교육 지원 확대 법안",
        startDate: new Date("2025-01-10"),
        endDate: new Date("2025-12-31"),
        proposerImageUrl: "https://randomuser.me/api/portraits/women/44.jpg",
        mainProposer: "이교육",
        proposerParty: "더불어민주당",
        proposers: [
          { id: "8", name: "이교육", party: "더불어민주당" },
          { id: "9", name: "박학생", party: "더불어민주당" },
          { id: "10", name: "정선생", party: "더불어민주당" },
        ],
        proposerDate: new Date("2024-12-01"),
        committee: "교육위원회",
        currentStep: "본회의 통과",
        stepLog: ["제안", "위원회 심사", "본회의 의결"],
        summary: "초중고 학생들을 위한 교육 지원 예산을 확대하는 법안입니다.",
        agreeRatio: 85,
        opposeRatio: 15,
        detailUrl: "#",
        commentsUrl: "#",
      },
      {
        billNo: "100008",
        viewCount: 75,
        commentsCount: 30,
        title: "청년 창업 지원 법안",
        startDate: new Date("2025-02-15"),
        endDate: new Date("2025-08-15"),
        proposerImageUrl: "https://randomuser.me/api/portraits/men/23.jpg",
        mainProposer: "김창업",
        proposerParty: "정의당",
        proposers: [{ id: "11", name: "김창업", party: "정의당" }],
        proposerDate: new Date("2025-02-01"),
        committee: "산업통상자원위원회",
        currentStep: "심사중",
        stepLog: ["제안", "위원회 심사"],
        summary: "청년 창업가들을 위한 금융 및 멘토링 지원 법안입니다.",
        agreeRatio: 65,
        opposeRatio: 35,
        detailUrl: "#",
        commentsUrl: "#",
      },
      {
        billNo: "100009",
        viewCount: 10,
        commentsCount: 0,
        title: "농업 보조금 축소 법안",
        startDate: new Date("2025-01-01"),
        endDate: new Date("2025-06-30"),
        proposerImageUrl: "https://randomuser.me/api/portraits/women/50.jpg",
        mainProposer: "최농부",
        proposerParty: "무소속",
        proposers: [{ id: "12", name: "최농부", party: "무소속" }],
        proposerDate: new Date("2024-12-20"),
        committee: "농림축산식품해양수산위원회",
        currentStep: "위원회 계류",
        stepLog: ["제안"],
        summary: "농업 보조금을 축소하여 재정 건전성을 도모하는 법안입니다.",
        agreeRatio: 40,
        opposeRatio: 60,
        detailUrl: "#",
        commentsUrl: "#",
      },
      {
        billNo: "100010",
        viewCount: 5,
        commentsCount: 2,
        title: "디지털 경제 활성화 법안",
        startDate: new Date("2025-04-01"),
        endDate: new Date("2025-10-01"),
        proposerImageUrl: "https://randomuser.me/api/portraits/men/77.jpg",
        mainProposer: "박디지털",
        proposerParty: "더불어민주당",
        proposers: [{ id: "13", name: "박디지털", party: "더불어민주당" }],
        proposerDate: new Date("2025-03-15"),
        committee: "과학기술정보방송통신위원회",
        currentStep: "심사중",
        stepLog: ["제안", "위원회 심사"],
        summary: "디지털 경제 발전과 혁신을 촉진하는 법안입니다.",
        agreeRatio: 55,
        opposeRatio: 45,
        detailUrl: "#",
        commentsUrl: "#",
      },
    ],
  };
}
