version: "3.8"

services:
  gov-watcher-fe:
    image: dlaudfuf33/gov-watcher-fe:latest
    container_name: gov-watcher-fe
    restart: always
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
      - VIRTUAL_HOST=govwhatsup.com
      - LETSENCRYPT_HOST=govwhatsup.com
      - LETSENCRYPT_EMAIL=dlaudfuf33@gmail.com
    expose:
      - "3000"
    networks:
      - proxy-tier
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  proxy-tier:
    external: true
