blank_issues_enabled: false
contact_links: []

issue_templates:
  - name: "\U0001F41E Bug Report"
    description: "버그/오류를 제보합니다 (UI 깨짐, 기능 이상 등)"
    labels: ["bug"]
    file: bug_report.md

  - name: "\U0001F4A1 Feature Request"
    description: "기능 추가나 개선 아이디어를 제안합니다"
    labels: ["feature"]
    file: feature_request.md
