import type { Politician } from "./politiciansType";

// 더미 데이터 생성
export const Politicians: Politician[] = [
  {
    id: "1",
    name: "김민수",
    party: "더불어민주당",
    district: "서울 강남구",
    position: "국회의원",
    term: 21,
    recentBills: 15,
    profileImage: "https://randomuser.me/api/portraits/men/14.jpg",
    passRate: 75,
    careerYears: 12,
    recentActivities: 28,
  },
  {
    id: "2",
    name: "이지원",
    party: "국민의힘",
    district: "부산 해운대구",
    position: "국회의원",
    term: 21,
    recentBills: 8,
    profileImage: "https://randomuser.me/api/portraits/women/11.jpg",
    passRate: 62,
    careerYears: 8,
    recentActivities: 15,
  },
  {
    id: "3",
    name: "박서연",
    party: "정의당",
    district: "경기 성남시",
    position: "국회의원",
    term: 21,
    recentBills: 22,
    profileImage: "https://randomuser.me/api/portraits/women/1.jpg",
    passRate: 85,
    careerYears: 6,
    recentActivities: 32,
  },
  {
    id: "4",
    name: "최준호",
    party: "기본소득당",
    district: "비례대표",
    position: "국회의원",
    term: 21,
    recentBills: 18,
    profileImage: "https://randomuser.me/api/portraits/women/12.jpg",
    passRate: 70,
    careerYears: 4,
    recentActivities: 25,
  },
  {
    id: "5",
    name: "정다은",
    party: "무소속",
    district: "인천 남동구",
    position: "국회의원",
    term: 21,
    recentBills: 10,
    profileImage: "https://randomuser.me/api/portraits/men/14.jpg",
    passRate: 60,
    careerYears: 10,
    recentActivities: 18,
  },
  {
    id: "6",
    name: "한승우",
    party: "더불어민주당",
    district: "대전 서구",
    position: "국회의원",
    term: 21,
    recentBills: 12,
    profileImage: "https://randomuser.me/api/portraits/men/61.jpg",
    passRate: 68,
    careerYears: 14,
    recentActivities: 22,
  },
  {
    id: "7",
    name: "송미영",
    party: "국민의힘",
    district: "대구 수성구",
    position: "국회의원",
    term: 21,
    recentBills: 7,
    profileImage: "https://randomuser.me/api/portraits/women/31.jpg",
    passRate: 72,
    careerYears: 6,
    recentActivities: 14,
  },
  {
    id: "8",
    name: "임재현",
    party: "더불어민주당",
    district: "광주 북구",
    position: "국회의원",
    term: 21,
    recentBills: 20,
    profileImage: "https://randomuser.me/api/portraits/men/71.jpg",
    passRate: 78,
    careerYears: 8,
    recentActivities: 30,
  },
  {
    id: "9",
    name: "오세진",
    party: "국민의힘",
    district: "울산 남구",
    position: "국회의원",
    term: 21,
    recentBills: 5,
    profileImage: "https://randomuser.me/api/portraits/men/17.jpg",
    passRate: 65,
    careerYears: 4,
    recentActivities: 12,
  },
  {
    id: "10",
    name: "윤하은",
    party: "정의당",
    district: "비례대표",
    position: "국회의원",
    term: 21,
    recentBills: 25,
    profileImage: "https://randomuser.me/api/portraits/women/26.jpg",
    passRate: 80,
    careerYears: 10,
    recentActivities: 35,
  },
  {
    id: "11",
    name: "강민재",
    party: "더불어민주당",
    district: "경남 창원시",
    position: "국회의원",
    term: 21,
    recentBills: 14,
    profileImage: "https://randomuser.me/api/portraits/men/77.jpg",
    passRate: 73,
    careerYears: 12,
    recentActivities: 24,
  },
  {
    id: "12",
    name: "조은지",
    party: "국민의힘",
    district: "경북 포항시",
    position: "국회의원",
    term: 21,
    recentBills: 9,
    profileImage: "https://randomuser.me/api/portraits/men/17.jpg",
    passRate: 67,
    careerYears: 6,
    recentActivities: 16,
  },
];
